### ISSUE TITLE
ical feed broken in thunderbird+lightning (at least for me)

### ISSUE THREAD

**Issue by stephanlukasczyk** [IEEE-SB-Passau/pelican-ieee-passau#13]
Since the change to pelican, the [ical feed](https://ieee.uni-passau.de/events.ics) does not work in thunderbird+lightning for me any more. Didn't check the English feed, yet. The ics file provided by the site seems to be valid, as far as I could tell from looking at it.
Is this only for me, or does somebody else also encounter this problem?

**Comment by catdog2** [comment]
The date format seems to be wrong, see http://icalendar.org/iCalendar-RFC-5545/3-3-5-date-time.html

**Comment by catdog2** [comment]
Should be fixed now, please test

**Comment by stephanlukasczyk** [comment]
Works now, _but_ the for some reason the text in the SUMMARY field of the ics is proceeded by
`<p class"first last">` and also the description is exported instead of the head line of the event. At least my thunderbird shows this behaviour when looking, e.g., in the regular meeting of 2016-11-07
![cal](https://cloud.githubusercontent.com/assets/2920379/19673832/ba8ab86a-9a83-11e6-8c7c-0765b69bc7d6.jpg)
