### ISSUE TITLE
.htaccess rules not applied 

### ISSUE THREAD

**Issue by catdog2** [IEEE-SB-Passau/pelican-ieee-passau#14]
https://github.com/IEEE-SB-Passau/pelican-ieee-passau/blob/master/content/.htaccess which ends up in the root of the output directory is not applied, perhaps AllowOverride is wrongly set.

Example: 

https://ieee.uni-passau.de/en/feed/ should point to https://ieee.uni-passau.de/en/feeds/all-en.atom.xml (but gives 404)

There seems also be a rule which redirects everything under /de/ to // (301) which is probably defined somewhere else, please disable it. This also introduced a permanent redirect from /de/feed/ to /feed/... I added a new one from /feed/ to /feeds/all-de.atom.xml to conquer this…

**Comment by Inyokus** [comment]
Fixed.
