### ISSUE TITLE
Merge branch into master

### ISSUE THREAD

**Issue by stephanlukasczyk** [IEEE-SB-Passau/pelican-ieee-passau#5]
Is there any reason why we are doing everything on a branch instead of the master? If not, please tell me; then I'm going to merge the changes back into master, as they are already based on the top commit of master...

**Comment by catdog2** [comment]
No reason anymore, i simply started with this branch initially when i played with the importer script.

**Comment by stephanlukasczyk** [comment]
Ok. Then I'm going to merge the branches as soon as my clone is finished and we can then continue on master.

**Comment by stephanlukasczyk** [comment]
Merge is done, we can now work on master again. Closing this issue

**Comment by catdog2** [comment]
migration deleted
