### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by fheck** [IEEE-SB-Passau/pelican-ieee-passau#8]
The current ReadMe does not match the content of the repo and should be updated.

**Comment by fheck** [comment]
The submodule for image_precess plugin does not get initialized automatically in the process described.

**Comment by catdog2** [comment]
Can you be more specific?

**Comment by catdog2** [comment]
This was as afaik about the --recursive option for the submodules, this got added to the readme a long time ago.
