### ISSUE TITLE
Update sponsors and board pages 

### ISSUE THREAD

**Issue by fheck** [IEEE-SB-Passau/pelican-ieee-passau#9]
The board paged needs to be updated for the new term and the sponsors page needs some updating as well.

**Comment by stephanlukasczyk** [comment]
[ ] sponsors pages (responsible @fheck )
[ ] board page (responsible @stephanlukasczyk)

**Comment by stephanlukasczyk** [comment]
Board updated with  061e8a6

**Comment by stephanlukasczyk** [comment]
I think we now can close this
